LIBRETRO_COMM_DIR = $(SOURCE_DIR)/../libretro-common

SOURCES_C := $(SOURCE_DIR)/cpu.c \
	$(SOURCE_DIR)/gpu.c \
	$(SOURCE_DIR)/libretro.c

SOURCES_CXX := 

INCLUDES := -I$(LIBRETRO_COMM_DIR)/include

ifneq (,$(findstring msvc200,$(platform)))
INCLUDES += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif
